name: Build
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Build project in release state
        run: |
          make
          ./funEvalExpr -h
  macOS:
    runs-on: macos-12
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Build project in release state
        run: |
          make
          ./funEvalExpr -h
